name: nike_shoe_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  hexcolor: ^3.0.1
  animations: ^2.0.7
  flutter_svg: ^2.0.7
  fade_shimmer: ^2.2.0
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  flutter_appauth: ^6.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  supabase_auth_ui: ^0.2.1
  supabase_flutter: ^1.10.11
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  conditional_builder_null_safety: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/icons/
  #   - assets/images/images/